---


- name: "Backdraft dependencies playbook"
  hosts: all
  become: true
  tasks:
    # Homa
    - name: "Homa"
      apt:
        name: ['cmake', 'libmnl-dev']
    # docker
    - name: "install docker daemon and docker-compose"
      apt: # assume cache has been updated in previous steps
        name: ['docker', 'docker-compose']
    # install perf, linux-tools-generic
    - name: "install perf tool"
      shell: "apt install --yes linux-tools-$(uname -r)"
      ignore_errors: yes
    # protobuf
    - name: "install protobuf c++ dependency"
      apt:
        name: ['autoconf', 'automake', 'libtool', 'curl', 'make', 'g++', 'unzip']
    - name: "cloneing protobuf"
      git:
        repo: "https://github.com/google/protobuf.git"
        dest: "/opt/protobuf"
        clone: yes
        version: "aedb8d726c8d2a371d999354d44ca7e1bdbb1e73"
    - name: "building protobuf"
      shell: |
        ./autogen.sh
        ./configure
        make -j
        sudo make install
        sudo ldconfig
        # make check
      args:
        chdir: /opt/protobuf
        creates: /opt/protobuf/compile
    - name: "cloneing protobuf-c"
      git:
        repo: "https://github.com/protobuf-c/protobuf-c"
        dest: "/opt/protobuf-c"
        clone: yes
    - name: "building protobuf-c"
      shell: ./autogen.sh && ./configure && make && sudo make install
      args:
        chdir: /opt/protobuf-c
        creates: /opt/protobuf-c/build-aux/compile
    # GRUB
    - name: "change default grub file for reserving 1GB hugepages"
      shell: 'echo GRUB_CMDLINE_LINUX_DEFAULT=\"default_hugepagesz=1G hugepagesz=1G hugepages=30\" | sudo tee -a /etc/default/grub'
    - name: "update grub"
      shell: "update-grub"
    # TODO: check if using mellanox NICs then install required files.


# setup BESS env
- import_playbook: bess-build-dep.yml
- import_playbook: bess-runtime.yml


# build repo
- import_playbook: build_repo.yml

# build apps
- name: "Backdraft make apps used in experiments"
  hosts: all
  become: false
  tasks:
    # tas container image
    # - name: "build `tas_container` docker image file"
    #   command: "../../code/apps/tas_container/build.sh"
    # build used applications
    # - name: "building applications (dpdk_netperf)"
    #   shell: ./make.sh
    #   args:
    #     chdir: ../../code/apps/dpdk_netperf/
    # - name: "building applications (udp_client_server)"
    #   shell: ./make.sh
    #   args:
    #     chdir: ../../code/apps/udp_client_server/

