earl3:
  ip: "192.168.1.1"
  mac: "b4:96:91:31:96:4c"
  hostname: earl-03-oob
  instances:
    - port: 1001
      ip: "192.168.1.11"
      app: "udp_app"
      type: "client"
      cpus: 3
      flow_config_name: "default_client"
      tas_cores: 1
      destinations:
        - earl4_0
earl4:
  ip: "192.168.1.2"
  mac: "b4:96:91:46:65:bc"
  hostname: earl-04-oob
  instances:
    - port: 2001
      ip: "192.168.1.21"
      type: "server"
      app: "udp_app"
      cpus: 5
      flow_config_name: "default_server"
      tas_cores: 1

