/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protobuf/bkdrft_msg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "bkdrft_msg.pb-c.h"
void   dpdk_net_perf__overlay__init
                     (DpdkNetPerf__Overlay         *message)
{
  static const DpdkNetPerf__Overlay init_value = DPDK_NET_PERF__OVERLAY__INIT;
  *message = init_value;
}
size_t dpdk_net_perf__overlay__get_packed_size
                     (const DpdkNetPerf__Overlay *message)
{
  assert(message->base.descriptor == &dpdk_net_perf__overlay__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dpdk_net_perf__overlay__pack
                     (const DpdkNetPerf__Overlay *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dpdk_net_perf__overlay__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dpdk_net_perf__overlay__pack_to_buffer
                     (const DpdkNetPerf__Overlay *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dpdk_net_perf__overlay__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DpdkNetPerf__Overlay *
       dpdk_net_perf__overlay__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DpdkNetPerf__Overlay *)
     protobuf_c_message_unpack (&dpdk_net_perf__overlay__descriptor,
                                allocator, len, data);
}
void   dpdk_net_perf__overlay__free_unpacked
                     (DpdkNetPerf__Overlay *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dpdk_net_perf__overlay__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dpdk_net_perf__ctrl__init
                     (DpdkNetPerf__Ctrl         *message)
{
  static const DpdkNetPerf__Ctrl init_value = DPDK_NET_PERF__CTRL__INIT;
  *message = init_value;
}
size_t dpdk_net_perf__ctrl__get_packed_size
                     (const DpdkNetPerf__Ctrl *message)
{
  assert(message->base.descriptor == &dpdk_net_perf__ctrl__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dpdk_net_perf__ctrl__pack
                     (const DpdkNetPerf__Ctrl *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dpdk_net_perf__ctrl__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dpdk_net_perf__ctrl__pack_to_buffer
                     (const DpdkNetPerf__Ctrl *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dpdk_net_perf__ctrl__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DpdkNetPerf__Ctrl *
       dpdk_net_perf__ctrl__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DpdkNetPerf__Ctrl *)
     protobuf_c_message_unpack (&dpdk_net_perf__ctrl__descriptor,
                                allocator, len, data);
}
void   dpdk_net_perf__ctrl__free_unpacked
                     (DpdkNetPerf__Ctrl *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dpdk_net_perf__ctrl__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor dpdk_net_perf__overlay__field_descriptors[5] =
{
  {
    "src_port",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DpdkNetPerf__Overlay, src_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dst_port",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DpdkNetPerf__Overlay, dst_port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "src_ip",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DpdkNetPerf__Overlay, src_ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dst_ip",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DpdkNetPerf__Overlay, dst_ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wnd_size",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DpdkNetPerf__Overlay, wnd_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dpdk_net_perf__overlay__field_indices_by_name[] = {
  3,   /* field[3] = dst_ip */
  1,   /* field[1] = dst_port */
  2,   /* field[2] = src_ip */
  0,   /* field[0] = src_port */
  4,   /* field[4] = wnd_size */
};
static const ProtobufCIntRange dpdk_net_perf__overlay__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor dpdk_net_perf__overlay__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dpdk_net_perf.Overlay",
  "Overlay",
  "DpdkNetPerf__Overlay",
  "dpdk_net_perf",
  sizeof(DpdkNetPerf__Overlay),
  5,
  dpdk_net_perf__overlay__field_descriptors,
  dpdk_net_perf__overlay__field_indices_by_name,
  1,  dpdk_net_perf__overlay__number_ranges,
  (ProtobufCMessageInit) dpdk_net_perf__overlay__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dpdk_net_perf__ctrl__field_descriptors[3] =
{
  {
    "qid",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DpdkNetPerf__Ctrl, qid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nb_pkts",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DpdkNetPerf__Ctrl, nb_pkts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "total_bytes",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DpdkNetPerf__Ctrl, total_bytes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dpdk_net_perf__ctrl__field_indices_by_name[] = {
  1,   /* field[1] = nb_pkts */
  0,   /* field[0] = qid */
  2,   /* field[2] = total_bytes */
};
static const ProtobufCIntRange dpdk_net_perf__ctrl__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dpdk_net_perf__ctrl__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dpdk_net_perf.Ctrl",
  "Ctrl",
  "DpdkNetPerf__Ctrl",
  "dpdk_net_perf",
  sizeof(DpdkNetPerf__Ctrl),
  3,
  dpdk_net_perf__ctrl__field_descriptors,
  dpdk_net_perf__ctrl__field_indices_by_name,
  1,  dpdk_net_perf__ctrl__number_ranges,
  (ProtobufCMessageInit) dpdk_net_perf__ctrl__init,
  NULL,NULL,NULL    /* reserved[123] */
};
