# A memcached client-server (small RPC) running
# in same network as shuffle (large RPC)

node0:
  ip: "192.168.1.1"
  mac: "9c:dc:71:4a:3c:f1"
  instances:
    - port: 11211  # port does not override mutilate port
      ip: "192.168.1.11"
      app: "memcached"
      type: "client"
      cpus: 1,2,3
      flow_config_name: "default_client"
      tas_cores: 1
      destinations:
        - node1_0
    - port: 1234 # shuffle client
      ip: "192.168.1.12"
      app: "shuffle"
      type: "client"
      cpus: 4,5,6 
      flow_config_name: "default_client"
      tas_cores: 1
      destinations:
        - node1_1
    - port: 1234 # shuffle client
      ip: "192.168.1.13"
      app: "shuffle"
      type: "client"
      cpus: 7,8,9
      flow_config_name: "default_client"
      tas_cores: 1
      destinations:
        - node1_2
node1:
  ip: "192.168.1.2"
  mac: "98:f2:b3:c8:b8:b5"
  instances:
    - port: 2001  # port does not overrride memcached port
      ip: "192.168.1.21"
      type: "server"
      app: "memcached"
      cpus: 1,2,3
      flow_config_name: "default_server"
      tas_cores: 1
    - port: 5678
      ip: "192.168.1.22"
      type: "server"
      app: "shuffle"
      cpus: 4,5,6
      flow_config_name: "default_server"
      tas_cores: 1
    - port: 5679
      ip: "192.168.1.23"
      type: "server"
      app: "shuffle"
      cpus: 7,8,9
      flow_config_name: "default_server"
      tas_cores: 1
      
