# A multi-thread UDP app config
node1:
  ip: "192.168.1.1"
  # mac: "1c:34:da:41:ca:bc" for node 0 (100G)
  mac: "1c:34:da:41:d0:0c"
  instances:
    - port: 1001
      ip: "192.168.1.11"
      app: "udp_app"
      type: "client"
      cpus: 20,21,22,23,24,25,26,27
      flow_config_name: "default_client"
      count_queue: 8
      destinations:
        - node1_0
        - node1_0
        - node1_0
        - node1_0
        - node1_0
        - node1_0
        - node1_0
        - node1_0
    - port: 1009
      ip: "192.168.1.12"
      app: "udp_app"
      type: "client"
      cpus: 28,29,30,31 #,16,17,18,19
      flow_config_name: "default_client"
      count_queue: 4
      destinations:
        - node1_0
        - node1_0
        - node1_0
        - node1_0
          # - node1_0
          # - node1_0
          # - node1_0
          # - node1_0
node2:
  ip: "192.168.1.2"
  mac: "1c:34:da:41:c6:fc"
  instances:
    - port: 3003
      ip: "192.168.1.21"
      type: "server"
      app: "udp_app"
      cpus: 20,21,22,23,24,25,26,27
      count_queue: 8
      flow_config_name: "default_server"
    - port: 4004
      ip: "192.168.1.22"
      type: "server"
      app: "udp_app"
      cpus: 28,29,30,31 #,16,17,18,19
      flow_config_name: "default_server"
      count_queue: 4

